/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "testmain.check" instead.
 */

#include <check.h>

#line 1 "testmain.check"
#include "index.h"
#include "error.h"
#include <stdio.h>

START_TEST(test_serial)
{
#line 6
    Index_ptr index;
    int i,j;
    fail_unless((index=createNodeIndex())!=NULL);
    for(i=0;i<1000;i++){
        fail_unless(insertNode(index,i)==OK_SUCCESS);
        for(j=0;j<100;j++){
            if(j%2==0)
                fail_unless(add_edge(index,i,i+j)==OK_SUCCESS);
        }
    }
    for(i=0;i<1000;i++)
        for(j=0;j<100;j++){
            if(j%2==0)
                fail_unless(edge_exists(index,i,i+j)==1);
            else
                fail_unless(edge_exists(index,i,i+j)==0);
        }
    fail_unless(destroyNodeIndex(index)==OK_SUCCESS);
    puts("test with 1000 serial inserts and 100 neighbors finished ");
}
END_TEST

START_TEST(test_step10)
{
#line 26
    Index_ptr index;
    int i,j,start;
    fail_unless((index=createNodeIndex())!=NULL);
    for(start=0;start<10;start++){
        for(i=start;i<1000;i+=10){
            fail_unless(insertNode(index,i)==OK_SUCCESS);
            for(j=0;j<100;j++){
                if(j%2==0)
                    fail_unless(add_edge(index,i,i+j)==OK_SUCCESS);
            }
        }
    }
    for(start=0;start<10;start++){
        for(i=start;i<1000;i+=10)
            for(j=0;j<100;j++){
                if(j%2==0)
                    fail_unless(edge_exists(index,i,i+j)==1);
                else
                    fail_unless(edge_exists(index,i,i+j)==0);
            }
    }
    fail_unless(destroyNodeIndex(index)==OK_SUCCESS);
    puts("test with 1000 inserts step 10 and 100 neighbors finished ");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_serial);
    tcase_add_test(tc1_1, test_step10);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
